# Generated by Django 2.2.5 on 2019-10-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dl',
            name='selesai',
            field=models.BooleanField(default=False),
        ),
    ]
