# Generated by Django 2.2.5 on 2019-10-19 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deadline', '0003_auto_20191019_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dl',
            name='nama_deadline',
            field=models.CharField(blank=True, max_length=25, verbose_name=''),
        ),
    ]
