# Generated by Django 2.2.5 on 2019-12-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='semester',
            field=models.DecimalField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (-1, 'Not a College Student')], decimal_places=0, default=1, max_digits=1),
        ),
    ]
