# Generated by Django 2.2.5 on 2019-12-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0002_profile_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='motto',
            field=models.TextField(max_length=100),
        ),
    ]
