# Generated by Django 2.2.5 on 2019-12-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0003_auto_20191206_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='nama',
            field=models.CharField(default='kosong', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='kosong', max_length=30),
        ),
    ]
