# Generated by Django 2.2.5 on 2019-12-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0005_auto_20191206_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', help_text='Optional', upload_to=''),
        ),
    ]
