# Generated by Django 2.2.5 on 2019-12-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0006_auto_20191206_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='thumb',
        ),
        migrations.AlterField(
            model_name='profile',
            name='nama',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
    ]
