# Generated by Django 2.2.5 on 2019-12-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profil', '0007_auto_20191213_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='semester',
            field=models.DecimalField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (-1, 'Not a College Student')], decimal_places=0, default=1, max_digits=1),
        ),
    ]
